name: Infrastructure Deploy

on:
  push:
    paths:
    - '**.bicep' # Should only run when an infra template changes
    - '**/infrastructure-deploy.yaml'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      BICEP_INPUT_PARAMETERS_JSON: ${{ secrets.BICEP_INPUT_PARAMETERS_JSON }}      
    steps:

    - name: Az CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure Bicep Build
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        ./bicep build $GITHUB_WORKSPACE/infrastructure/main.bicep      

    - name: Deploy Bicep template
      run: |
        az deployment group create -g "${{ secrets.RESOURCE_GROUP_NAME }}" --template-file $GITHUB_WORKSPACE/infrastructure/main.json --parameters "${{ env.BICEP_INPUT_PARAMETERS_JSON }}"

    #- name: Az CLI Resource Group Deployment
    #  uses: azure/CLI@v1
    #  with:
    #    azcliversion: 2.22.1
    #    inlineScript: |
    #      az deployment group create -g "${{ env.RESOURCE_GROUP_NAME }}" --template-file $GITHUB_WORKSPACE/infrastructure/main.bicep --parameters "${{ env.BICEP_INPUT_PARAMETERS_JSON }}"